# Usa una imagen oficial de Python
FROM python:3.12-slim

# Crea carpeta de trabajo
WORKDIR /usr/src/app

# Copia los archivos de tu bot
COPY . .

# Instala dependencias (si las hubiera)
RUN pip install --no-cache-dir -r requirements.txt

# Comando de inicio
CMD ["python3", "bot.py"]
